run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - stylecheck
    - gosec
    - misspell
    - unconvert
    - unparam
    - prealloc
    - exportloopref
    - gocyclo
    - gocritic
    - revive
    - bodyclose
    - nilerr
    - errorlint
    - goconst

linters-settings:
  gocyclo:
    min-complexity: 15
  
  govet:
    check-shadowing: true
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gosec:
    excludes:
      - G404  # Use of weak random number generator - we use crypto/rand
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst
    
    # Exclude known false positives
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Exclude shadow checking on err variables (common pattern)
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true